### ISSUE TITLE
Can't find `lib.es5.d.ts`

### ISSUE THREAD

**Issue by lukeautry** [CyriacBr/es5-to-dts#1]
When running from the command line, I get this error:

`Error: ENOENT: no such file or directory, open '<workspace_dir>/node_modules/es5-to-dts/node_modules/typescript/lib/lib.es5.d.ts'`

**Comment by CyriacBr** [comment]
Oh, that file was inside typescript node_modules folder. Give me a minute I'll fix it right away.

**Comment by CyriacBr** [comment]
@lukeautry Seems to be ok now.

**Comment by HIMISOCOOL** [comment]
have you pushed this fix to npm yet?

**Comment by CyriacBr** [comment]
Yes, let me know if it works for you now. It should.

**Comment by HIMISOCOOL** [comment]
it still has that error for me
λ npm list -g es5-to-dts
`-- es5-to-dts@1.0.1

Error: ENOENT: no such file or directory, open '~\npm\node_modules\es5-to-dts\node_modules\typescript\lib\lib.es5.d.ts'

the file is there in that folder though so its a bit confusing

**Comment by CyriacBr** [comment]
@HIMISOCOOL I published a new version.

**Comment by HIMISOCOOL** [comment]
```
C:\Workspace> npm -g uninstall es5-to-dts
removed 34 packages in 0.62s
C:\Workspace> npm install -g es5-to-dts@latest
C:\...\...\AppData\Roaming\npm\es5-to-dts -> C:\...\...\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js
+ es5-to-dts@1.0.2
added 34 packages from 62 contributors in 1.596s
C:\Workspace> npm list -g es5-to-dts
C:\...\...\AppData\Roaming\npm
`-- es5-to-dts@1.0.2

C:\Workspace> es5-to-dts vuex.esm.js vuex
An error occured.
C:\...\...\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:475
    throw error;
    ^

Error: ENOENT: no such file or directory, open 'C:\...\...\AppData\Roaming\npm\node_modules\es5-to-dts\lib\lib.es5.d.ts'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (C:\...\...\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:455:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
C:\Workspace>
```

**Comment by CyriacBr** [comment]
I'll have to look into it more, but that's odd.

**Comment by CyriacBr** [comment]
@HIMISOCOOL Btw, while using this tool to generate the d.ts file of vuex.esm.js I identified a few other patterns. I'm going to update the package to support them and fix the issue you reported.

**Comment by HIMISOCOOL** [comment]
@CyriacBr I just chose the vuex cause it's really hard to make types for manually, good to hear

**Comment by CyriacBr** [comment]
@HIMISOCOOL Package updated.I swear it is ok now haha! Have fun.

Here is the generated d.ts for vuex:
```typescript
declare global {
    interface store {
        _devtoolHook: any;
        _actions: any;
        _mutations: any;
        _wrappedGetters: any;
        _modulesNamespaceMap: any;
        getters: {};
        _vm: any;
    }
}
export declare namespace Vuex {
    /**
     * vuex v3.1.0
     * (c) 2019 Evan You
     * @license MIT
     */
    function applyMixin();

    function devtoolPlugin(store: any);
    /**
     * forEach for object
     */
    function forEachValue();

    function isObject(obj: any);

    function isPromise(val: any);

    function assert(condition: any, msg: any);

    function update(path: any, targetModule: any, newModule: any);

    function assertRawModule(path: any, rawModule: any);

    function makeAssertionMessage(path: any, key: any, type: any, value: any, expected: any);

    function genericSubscribe(fn: any, subs: any);

    function resetStore(store: any, hot: any);

    function resetStoreVM(store: any, state: any, hot: any);

    function installModule(store: any, rootState: any, path: any, module: any, hot: any);
    /**
     * make localized dispatch, commit, getters and state
     * if there is no namespace, just use root ones
     */
    function makeLocalContext();

    function makeLocalGetters(store: any, namespace: any);

    function registerMutation(store: any, type: any, handler: any, local: any);

    function registerAction(store: any, type: any, handler: any, local: any);

    function registerGetter(store: any, type: any, rawGetter: any, local: any);

    function enableStrictMode(store: any);

    function getNestedState(state: any, path: any);

    function unifyObjectStyle(type: any, payload: any, options: any);

    function install(_Vue: any);
    /**
     * Rebinding namespace param for mapXXX function in special scoped, and return them by simple object
     * @param {String} namespace
     * @return {Object}
     */
    function createNamespacedHelpers(namespace: string);
    /**
     * Normalize the map
     * normalizeMap([1, 2, 3]) => [ { key: 1, val: 1 }, { key: 2, val: 2 }, { key: 3, val: 3 } ]
     * normalizeMap({a: 1, b: 2, c: 3}) => [ { key: 'a', val: 1 }, { key: 'b', val: 2 }, { key: 'c', val: 3 } ]
     * @param {Array|Object} map
     * @return {Object}
     */
    function normalizeMap(map: any[] | Object);
    /**
     * Return a function expect two param contains namespace and map. it will normalize the namespace and then the param's function will handle the new namespace and the map.
     * @param {Function} fn
     * @return {Function}
     */
    function normalizeNamespace(fn: Function);
    /**
     * Search a special module from store by namespace. if module not exist, print error message.
     * @param {Object} store
     * @param {String} helper
     * @param {String} namespace
     * @return {Object}
     */
    function getModuleByNamespace(store: Object, helper: string, namespace: string);
    class Module {
        new(rawModule: any, runtime: any);
        addChild: (key: any, module: any) => void;

        removeChild: (key: any) => void;

        getChild: (key: any) => any;

        update: (rawModule: any) => void;

        forEachChild: (fn: any) => void;

        forEachGetter: (fn: any) => void;

        forEachAction: (fn: any) => void;

        forEachMutation: (fn: any) => void;
    }
    class ModuleCollection {
        new(rawRootModule: any);
        get: (path: any) => any;

        getNamespace: (path: any) => any;

        update: (rawRootModule: any) => void;

        register: (path: any, rawModule: any, runtime: any) => void;

        unregister: (path: any) => void;
    }
    class Store {
        new(options: any);
        commit: (_type: any, _payload: any, _options: any) => void;

        dispatch: (_type: any, _payload: any) => any;

        subscribe: (fn: any) => () => void;

        subscribeAction: (fn: any) => () => void;

        watch: (getter: any, cb: any, options: any) => any;

        replaceState: (state: any) => void;

        registerModule: (path: any, rawModule: any, options: any) => void;

        unregisterModule: (path: any) => void;

        hotUpdate: (newOptions: any) => void;

        _withCommit: (fn: any) => void;

        _committing: boolean;
    }
}
```

**Comment by HIMISOCOOL** [comment]
```
C:\Workspace> es5-to-dts vuex.esm.js vuex
 - TS program created
 - Collecting properties
 -> Done
 - Collecting pseudo classes
An error occured.
C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:508
    throw error;
    ^

TypeError: type.isLiteral is not a function
    at getTypeString (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:368:14)
    at makeVariablesFromParameters (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:349:19)
    at visit (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:138:35)
    at visitNodes (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:11909:30)
    at Object.forEachChild (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:12087:24)
    at traverseProgram (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:359:16)
    at makePseudoClasses (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:279:5)
    at Object.<anonymous> (C:\Users\MatthewMe\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:497:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
C:\Workspace>
```

but a new error counts as progress.
Also thanks for running the file :)

**Comment by CyriacBr** [comment]
It is expected to have some errors depending on the patterns it can't find.
Please open a new issue about it, I'll take a look later when I have the
time :)

**Comment by HIMISOCOOL** [comment]
moved my comment to a new issue #2
