### ISSUE TITLE
TypeError: type.isLiteral is not a function

### ISSUE THREAD

**Issue by HIMISOCOOL** [CyriacBr/es5-to-dts#2]
```
C:\Workspace> es5-to-dts vuex.esm.js vuex
 - TS program created
 - Collecting properties
 -> Done
 - Collecting pseudo classes
An error occured.
C:\..\..\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:508
    throw error;
    ^

TypeError: type.isLiteral is not a function
    at getTypeString (C:\..\..\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:368:14)
    at makeVariablesFromParameters (C:\..\..\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:349:19)
    at visit (C:\..\..\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:138:35)
    at visitNodes (C:\..\..\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:11909:30)
    at Object.forEachChild (C:\..\..\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:12087:24)
    at traverseProgram (C:\..\..\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:359:16)
    at makePseudoClasses (C:\..\..\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:279:5)
    at Object.<anonymous> (C:\..\..\AppData\Roaming\npm\node_modules\es5-to-dts\dist\script.js:497:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
C:\Workspace>
```

Hey there @CyriacBr above is the error I see when running it over vue.esm.js

**Comment by CyriacBr** [comment]
Hey.
I just updated the package. Now errors encountered during generation are skipped and archived for later analysis. You'll still get a good chunk of the code generated.
Please try to update the package and let me know the logs if that error appears again.
![Error handling](https://i.imgur.com/ue7EJDu.png)

**Comment by HIMISOCOOL** [comment]
oh sweet that's a great Idea.
I'm confused as to how you made the output for the vuex file since I get a huge number of errors
```
C:\Workspace> es5-to-dts .\vuex.esm.js Vuex
× Collecting properties | 29 error(s)
× Collecting pseudo classes | 29 error(s)
```
heres the log
[log.txt](https://github.com/CyriacBr/es5-to-dts/files/2964188/log.txt)

**Comment by CyriacBr** [comment]
Which version of typescript are you using? It seems like yours doesn't handle some of the compiler methods I am using.

**Comment by HIMISOCOOL** [comment]
oh right it needs to be installed globally at 3+ 🙃, perhaps it's worth adding it as a part of the installation steps

**Comment by CyriacBr** [comment]
I will in the next update. Thanks for your interest so far.
